#!/bin/bash
# =============================================================================
# config/bash_init.sh
# Common shell initialization for Docker development environment
#
# Sets up core environment variables and sources dependent configuration files
# to ensure a consistent developer experience across ROS1 and ROS2 targets.
# =============================================================================

# ccache
export PATH="/usr/lib/ccache:$PATH"
export CCACHE_DIR=/cache/ccache

# uv (Python)
export UV_CACHE_DIR=/cache/uv
export UV_PYTHON=${UV_PYTHON:-3.10}
export UV_PROJECT_ENVIRONMENT="/workspace/install/.venv"

# C++ Standard
export CMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD:-17}

# Custom Aliases
source /docker_dev/config/aliases.sh

# GPU Environment Variables (Dynamically generated by entrypoint.sh or gpu_setup.sh)
if [ -f /root/.gpu_env.sh ]; then
source /root/.gpu_env.sh
fi

# Auto-activate uv Virtual Environment (.venv)
if [ -f "/workspace/install/.venv/bin/activate" ]; then
    source "/workspace/install/.venv/bin/activate"
fi

# Welcome Message (MOTD)
if [ -f /docker_dev/scripts/welcome.sh ]; then
    bash /docker_dev/scripts/welcome.sh
fi

# Shell Prompt
export PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "

# =============================================================================
# ROS Environment (Common for ROS1 & ROS2)
# =============================================================================

# Dynamic Sourcing of ROS Core Environment
if [ -f "/opt/ros/${ROS_DISTRO:-humble}/setup.bash" ]; then
    source /opt/ros/${ROS_DISTRO:-humble}/setup.bash
fi

# Workspace Overlay (Automatically sourced after colcon build)
if [ -f /workspace/install/setup.bash ]; then
    source /workspace/install/setup.bash
fi

# Colcon Argument Completion
if [ -f /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash ]; then
    source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
fi

# ROS Version-specific Configuration
if [ "${ROS_DISTRO}" = "noetic" ]; then
    # Prioritize environment variables injected by Docker Compose, fallback to defaults
    export ROS_MASTER_URI=${ROS_MASTER_URI:-http://localhost:11311}
    export ROS_HOSTNAME=${ROS_HOSTNAME:-localhost}
else
    # ROS 2 (Humble) Specifics
    export RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    export ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
fi
